name: run

on:
  workflow_dispatch:
  push:

jobs:
  list:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix
        run: echo "matrix=$(find . -iname run.sh | sed 's|^\./||' | xargs dirname | jq -R -s -c 'split("\n") | map(select(length > 0))')" >> $GITHUB_OUTPUT
  run:
    needs: list
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: ${{ fromJson(needs.list.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - name: run ${{ matrix.dir }}
        run: (cd ${{ matrix.dir }}; ./run.sh)
